import mongoose from "mongoose";

const CommercialPerformaSchema = new mongoose.Schema(
  {
    otp: String,
    TDPIC: String, 
    clientId: String,
    clientEmail: String,
    clientAddress: String,
    clientState: String,
    clientPinCode: String,
    proposalDate: {
      type: Date,
      default: Date.now,
    },
    hsnsacCode2: String,
    hsnsacCode2Inverter: String,
    hsnsacCode2Solar: String,
    systemType: String,
    systemConnection: String,
    gridType: String,
    modQUnit1: String,
    modBrand1: String,
    modType1: String,
    modTech1: String,
    modRating1: Number,
    modQuantity1: Number,
    invBrand4: String,
    invRating4: Number,
    invQuantity4: String,
    invQUnit4: String,
    finalPrice: Number,
    supplyPercentage: Number,
    electricSupply: String,
    clientMobile: String,
    clientName: String,
    batteryBrand: String,
    batteryType: String,
    batteryCapacity: String,
    batteryQuantity: String,
    clientIdType: String,
    invoiceGeneratedBy: String,
    pricePerWattIncGst: Number,
    totalKW: Number,
    mat1Required3: String,
    mat1Quantity3: String,
    mat1QUnit3: String,
    mat2Required5: String,
    mat2Quantity5: String,
    mat2QUnit5: String,
    busMcbRequired6: String,
    busMcbQuantity6: String,
    busMcbQUnit6: String,
    fireERequired7: String,
    fireEQuantity7: String,
    fireEQUnit7: String,
    autoCleanRequired8: String,
    autoCleanQuantity8: String,
    autoCleanQUnit8: String,
    stRoofRequired2: String,
    stRoofQuantity2: String,
    stRoofQUnit2: String,
    stTinRequired2: String,
    stTinQuantity2: String,
    stTinQUnit2: String,
    formType: String,
  },
  {
    timestamps: true,
  }
);

const CommercialPerforma = mongoose.model(
  "CommercialPerforma",
  CommercialPerformaSchema
);

export default CommercialPerforma;
